name: alafein
description: "A new Flutter project."
publish_to: "none"

version: 1.0.7+5

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  auto_size_text_field: ^2.2.2
  flutter_facebook_auth: ^6.2.0
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  dropdown_button3: ^3.0.0
  equatable: ^2.0.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.16
  flutter:
    sdk: flutter
  flutter_animate: ^4.4.1
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  gap: ^3.0.1
  get_it: ^7.6.4
  google_fonts: 6.1.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  http: ^1.2.0
  image_picker: ^1.0.7
  json_annotation: ^4.8.1
  liquid_pull_to_refresh: ^3.0.1
  logger: ^2.0.2+1
  multi_select_flutter: ^4.1.3
  path: ^1.8.3
  path_provider: ^2.1.1
  responsive_builder: ^0.7.0
  sembast: ^3.5.0+1
  smooth_page_indicator: ^1.1.0
  svg_flutter: ^0.0.1
  url_launcher: ^6.2.4
  video_player: ^2.9.2
  add_2_calendar: ^3.0.1
  share_plus: ^7.2.2
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  easy_localization: ^3.0.7

dependency_overrides:
    video_player_android: 2.7.16

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/AlaFeinLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/placeholders/
    - assets/translations/
    - assets/images/Motion Graphics/all-set/gif/all-set.gif


  #   - images/a_dot_ham.jpeg
  fonts:
    - family: FormulaCondensed
      fonts:
        - asset: assets/fonts/FormulaCondensed-Bold.otf
          weight: 900
        - asset: assets/fonts/FormulaCondensed-Light.otf
          weight: 100
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700