// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWtGpWFRGcb7EQM_T7nNrlM2ad-dTj1kQ',
    appId: '1:587761639039:android:230c35dde1a21f7629a94a',
    messagingSenderId: '587761639039',
    projectId: 'alafein',
    storageBucket: 'alafein.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0cK_IGcj5nTxdag3j8Z8jB5fcu4yka0E',
    appId: '1:587761639039:ios:91b6e0a954c9e01229a94a',
    messagingSenderId: '587761639039',
    projectId: 'alafein',
    storageBucket: 'alafein.appspot.com',
    androidClientId: '587761639039-nme8uh34kc0h86eklfmpa7rpaerofkkv.apps.googleusercontent.com',
    iosClientId: '587761639039-g2l2j3h8ndrcpe4jq5jrse4h31t8k0vp.apps.googleusercontent.com',
    iosBundleId: 'com.alafeinteam.alafein',
  );
}
